### ISSUE TITLE
Add validation to record and/or protocol methods

### ISSUE THREAD

**Issue by dmitrig01** [Prismatic/schema#217] opened 2015-05-21 18:37 UTC
I've searched around for this and can't seem to find it –

It would be great to be able to validate functions defined in records, e.g.:
```
(defprotocol Foo (a [_ x]))
(s/defrecord Bar [b :- s/Str]
  (a :- s/Str
    [_ x :- s/Str]
    (str b x)))
```

**Comment by w01fe** [comment] 2015-05-21 18:47
Duplicate of #117

**Comment by dmitrig01** [comment] 2015-05-21 18:48
my bad - sorry :-)

**Closed by w01fe** 2015-05-21 18:47 UTC

**Comment by w01fe** [comment] 2015-05-21 19:41
No worries :)
